# 要拉取什么指数(确保指数代码正确)
codes:
  - sh000001: 上证指数
  - sz399001: 深证成指
  - sh000016: 上证50
  - sh000010: 上证180
  - sh000300: 上证300
  - sh000905: 中证500
  - sh000852: 中证1000
  - sz399006: 创业板指

# 要拉取什么类型的数据(日,周,月,季,年)
types:
#  - 日
#  - 周
#  - 月
#  - 季
#  - 年

# 自定义服务器地址
#hosts:
#  - 122.51.120.217

# 自定义文件名(保存路径)
#filename: ./data/{type}线/{code}({name}).csv